#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S2,     none,          sensorNone)
#pragma config(Sensor, S3,     none,          sensorNone)
#pragma config(Sensor, S4,     gyro,          sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define _Minigolf


const tSensors kGyroSensor = S4;      // Connect to port 3. Adjust as appropriate.

#include "test.c" // Muessen so in RobotC eingebunden werden :(
#include "Get_Distance.c"
#include "GyroDriver.c"
#include "Move_turn.c"

task main()
{
	float fOldAngle = -1;
	int iOldDistance = 0xFF;
	unsigned int i;

	unsigned int scannedDist[180];

	eraseDisplay();
	Dist_PowerOn();
	wait1Msec(11);


  nxtDisplayStringAt(0, 63, "Minigolf 2013");

  nxtDisplayStringAt(0, 48, "GyroSensor:");
  nxtDisplayStringAt(0, 40, "SonarSensor:");

	wait1Msec(1000);

	while (!bIsGyroInitialized())

	wait1Msec(2000); // Gyro initialisierung


	for(i=0;i<180;i++)
	{

		int sonarValue = GetDistance();
		if( sonarValue !=	iOldDistance)
		{
			nxtDisplayStringAt(62, 39, "  %2dmm   ", (long) sonarValue);
			iOldDistance = sonarValue;
			scannedDist[i] = sonarValue;
		}

		if (_fGyroAngle != fOldAngle)
    {
      nxtDisplayStringAt(62, 48, "  %3d Grad   ", (long)_fGyroAngle);
      fOldAngle = _fGyroAngle;
    }
    //turn_right(1);
    wait1Msec(200);
	}



	while(1)
	{
		//int sonarValue = GetDistance();
		int sonarValue = GetDistanceRead();
		if( sonarValue !=	iOldDistance)
		{
			nxtDisplayStringAt(62, 39, "  %2dmm   ", (long) sonarValue);
			iOldDistance = sonarValue;
		}

		if (_fGyroAngle != fOldAngle)
    {
      nxtDisplayStringAt(62, 48, "  %3d Grad   ", (long)_fGyroAngle);
      fOldAngle = _fGyroAngle;
    }
    wait1Msec(100);
    //turn_left(10);
	}
	Dist_PowerOff();
}
