#pragma config(Sensor, S1,     MSDIST,              sensorI2CCustomFastSkipStates9V)
#pragma config(Sensor, S2,     none,          sensorNone)
#pragma config(Sensor, S3,     none,          sensorNone)
#pragma config(Sensor, S4,     HTGYRO,          sensorAnalogInactive)
#pragma config(Motor,  motorA,          hitMotor,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//#pragma config(Sensor, S1,     sonar,          sensorSONAR) // OLD DRIVER "Distance_read.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define _Minigolf


//const tSensors kGyroSensor = S4;      // Connect to port 3. Adjust as appropriate.

//#include "Distance_read.c"
#include "DistDriver.c"
#include "GyroDriver.c"
#include "Move_turn.c"
#include "GeradeAusFahren.c"
#include "Ball_Schlagen.c"
#include "Search_Object.c"
#include "Math_func.c"

task main()
{
	int tempAngle;
	eraseDisplay();
	wait1Msec(11);

	nxtDisplayStringAt(0, 63, "Minigolf 2013");

	nxtDisplayStringAt(0, 48, "GyroSensor:");
	nxtDisplayStringAt(0, 40, "SonarSensor:");

	//StartTask(GyroDeviceDriver);
	StartTask(DistDeviceDriver);
	StartTask(getHeading);

	while(!_GyrodriverInitFinish) // Gyro initialisierung
	{
		EndTimeSlice();
	}
	tempAngle = (int)_fGyroAngle;
	wait1Msec(4000);
	while(tempAngle != (int)_fGyroAngle)
	{
			nxtDisplayStringAt(0, 48, "GYRO FAIL, %02d",(int)_fGyroAngle);
			nxtDisplayStringAt(0, 40, "Drift after INIT");
	}

	searchObjekt();
	wait1Msec(500);
	calc_koordinaten_Ball(_ObjectAngle,_ObjectDistance+45);
	wait1Msec(500);
	calc_degree_hit();
	wait1Msec(500);
	calc_koordinaten_Drive();
	wait1Msec(500);
	turn2Degree(900);
	wait1Msec(500);
	driveDistance(_distance_X2Drive);
	wait1Msec(500);
	turn2Degree(0);
	wait1Msec(500);
	driveDistance(_distance_Y2Drive);
	wait1Msec(500);
	turn2Degree(_degree_Hit);
	wait1Msec(500);
	driveDistance(50);
	wait1Msec(500);
	schlagen(40,60);

	while(1)
	{
		EndTimeSlice();
	}
	StopAllTasks();
}
