#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S2,     none,          sensorNone)
#pragma config(Sensor, S3,     none,          sensorNone)
#pragma config(Sensor, S4,     gyro,          sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors kGyroSensor = S4;      // Connect to port 3. Adjust as appropriate.

#include "test.c" // Muessen so in RobotC eingebunden werden :(

#include "GyroDriver.c"

task main()
{
	float fOldAngle = -1;
	int iOldDistance = 0xFF;

	eraseDisplay();
	wait1Msec(11);
	/*
	nSyncedMotors = synchBC; //motor B is the master, motor C is the slave
  nSyncedTurnRatio = -100; //motors move in opposite directions of each other

  motor[motorB] = 30; //turn motor B on, which controls motor C at 30% power
  wait1Msec(500);  // wait for one half second

  motor[motorB] = 0;  // turn the motors off.*/

  nxtDisplayStringAt(0, 63, "Minigolf 2013");

  nxtDisplayStringAt(0, 48, "GyroSensor:");
  nxtDisplayStringAt(0, 40, "SonarSensor:");

	wait1Msec(1000);

	while (!bIsGyroInitialized())

	while(1)
	{
		int sonarValue = SensorValue(sonar);
		if( sonarValue !=	iOldDistance)
		{
			nxtDisplayStringAt(62, 39, "  %2d   ", (long) sonarValue);
			iOldDistance = sonarValue;
		}

		if (fGyroAngle != fOldAngle)
    {
      nxtDisplayStringAt(62, 48, "  %3d   ", (long) fGyroAngle);
      fOldAngle = fGyroAngle;
    }
    wait1Msec(3);
	}
}
